export interface User {
    userId: number,
    userOutsideId: string,
    userName: string,
    emailAddress: string,
    firstName: string,
    lastName: string,
    userType: string,
    isActive: boolean,
    addressLine1: string,
    addressLine2: string,
    country: string,
    city: string,
    state: string,
    province: string,
    createdOn: Date,
    faxNumber: string,
    phoneNumber: string,
    postalCode: string,
}